theme: jekyll-theme-midnight

title: Juan Antonio Montenegro Marroquin
description: Data Scientist on the making, Economist and writterðŸ’»
             [Blog](https://lo-que-aprendi-hoy-en-data.ghost.io/ghost/), [email](juanmonte795@gmail.com), [GitHub](https://github.com/juananmonte)
timezone: Asia/Seoul
github:
  is_project_page: false
